

//路由都是动态加载


export default [
        {
            path:"/about",
            name:"about",
            component:()=>import("@/pages/about"),
            meta:{showFoot:true}
        },
        {
            path:"/center",
            name:"center",
            component:()=>import("@/pages/Center"),
            meta:{showFoot:true},
            //二级路由路径不用写/
            children:[
                {
                    path:"myorder",
                    name:"myorder",
                    component:()=>import("@/pages/Center/myorder"),
                    meta:{showFoot:true}
                },
                {
                    path:"group",
                    name:"group",
                    //路由懒加载，减少打包体积，原理是动态导入组件
                    component:()=>import("@/pages/Center/group"),
                    meta:{showFoot:true}

                },
                //重定向，默认到center组件，指定一个子组件
                {
                    path:"/center",
                    redirect:"/center/myorder"
                }
            ]
        },
        {
            path:"/paysuccess",
            name:"paysuccess",
            component:()=>import("../pages/PaySuccess/index.vue"),
            meta:{showFoot:true},
        },
        {
            path:"/pay",
            name:"pay",
            component:()=>import("@/pages/Pay"),
            meta:{showFoot:true},
            beforeEnter:(to,from,next)=>{
               if(from.path=="/trade"){
                next()
               }
               else{
                next(false)
               }
            }
        },
        {
            path:"/trade",
            name:"trade",
            component:()=>import("@/pages/Trade"),
            meta:{showFoot:true},
            //去交易页面，必须是从购物车来
            beforeEnter:(to,from,next)=>{
                if(from.path=="/shopcar"){
                    next()
                }
                else{
                    next(false)
                }
            }
        },
        {
            path:"/shopcar",
            name:"shopcar",
            component:()=>import("@/pages/ShopCar"),
            meta:{showFoot:true}
        },
        {
            name:"addCarSuccess",
            path:"/addCarSuccess",
            component:()=>import("@/pages/AddCartSuccess"),
            meta:{showFoot:true}
        },
        {
            name:"detail",
            path:"/detail:skuid?",
            component:()=>import("@/pages/Detail"),
            meta:{showFoot:true}
        },
        {
            name:"home",
            path:"/home",
            component:()=>import("@/pages/home"),
            meta:{
                showFoot:true
            }
        },
        {
            name:"search",
            path:"/search/:keyword?",
            component:()=>import("@/pages/search"),
            meta:{
                showFoot:true
            },
            props:({params:{keyword},meta:{showFoot}})=>{
                return {
                    keyword,
                    showFoot
                }
            }
        },
        {
            path:"/login",
            component:()=>import("@/pages/login"),
            meta:{
                showFoot:false,
                disshowTop:true
            }
        },
        {
            name:"register",
            path:"/register",
            component:()=>import("@/pages/register"),
            meta:{
                showFoot:false,
                disshowTop:true
            }
        },
        //一开始就定向到/home
        {
            path:"*",
            redirect:"/home"
        }
    ]
